### PR TITLE
update template for reveal.js 4.0.0

### PR DESCRIPTION
**Pull request by salim-b**
cf.
- https://github.com/hakimel/reveal.js/releases/tag/4.0.0
- https://revealjs.com/upgrading/

#### Remaining Issues

- [Fenced code blocks](https://pandoc.org/MANUAL.html#fenced-code-blocks) are not rendered properly. Someone more proficient needed to look into it.

- Maybe more, needs testing!

### CODE REVIEW

**Comment by jgm** [comment]
The problem with fenced code blocks is that you have the RevealHighlight plugin enabled.
Remove that.  Pandoc does its own highlighting, and the reveal highlighting interferes.
Otherwise it worked okay in my limited testing.  If you can do more testing, great!

**Comment by jgm** [comment]
By the way, this goes in pandoc, not this repo.

**Comment by jgm** [comment]
Another question is about the notes-server variable which used to do something but doesn't any more.  Should something be made conditional on this (the RevealNotes plugin)?  In any case the MANUAL.txt may need to be modified.

**Comment by salim-b** [comment]
> By the way, this goes in pandoc, not this repo.

Oh, alright! I've opened https://github.com/jgm/pandoc/pull/6390

> The problem with fenced code blocks is that you have the RevealHighlight plugin enabled.

Ahh, thanks, I've removed it.

> Another question is about the notes-server variable which used to do something but doesn't any more.  In any case the MANUAL.txt may need to be modified.

To cite the [reveal.js 4 upgrade instructions](https://revealjs.com/upgrading/#removed-multiplex-and-notes-server):

> The Multiplex and Notes Server plugins have moved out of reveal.js core to their own repositories.

The Notes Server is found [here](https://github.com/reveal/notes-server) now. Since I don't use it, I didn't bother.

> Should something be made conditional on this (the RevealNotes plugin)?

No, I don't think so. The RevealNotes plugin works without the server and [provides the speaker view](https://revealjs.com/plugins/#built-in-plugins).

> In any case the MANUAL.txt may need to be modified.

I've just scanned the manual for info regarding the speaker notes server and couldn't find anything (the word `server` is included exactly 0 times). The [section about speaker notes](https://pandoc.org/MANUAL.html#speaker-notes) doesn't say anything about the server.

**Pull request closed without merging**
