### PR TITLE
Render subtitle in LaTeX using titling package.

### PR DESCRIPTION
**Pull request by adunning**
This will not change the behaviour of packages that already define `\subtitle` (such as `scrartcl`), but will still allow it to be printed in a document class that does not provide it (such as the default `article`). If the `titling` package is not present, the user will receive `LaTeX Error: File `titling.sty' not found.`. This goes against standard practice somewhat, but will prevent the creation of documents that lack expected contents.

### CODE REVIEW

**Comment by adunning** [comment]
Note also that the contents of `providecommand` are ignored entirely if the command is already defined, meaning that one can still use `scrartcl` and provide a subtitle without having the `titling` package.

**Comment by adunning** [comment]
Modified to put the command back where it was before.

**Comment by jgm** [comment]
@xoolive you have a point, this might class with stylesheets that redefine `\maketitle` without defining `\subtitle`.  On the other hand, the HTML templates do print a subtitle by default, and people might well expect that in PDF/LaTeX.

> the information is still set somewhere in the pdf properties;

Actually it isn't, anymore.  We could restore setting `subject` to the subtitle, but I'm not sure that really made much sense to begin with.  Or we could set the PDF title property to a combination of title and subtitle.

**Comment by xoolive** [comment]
@jgm I think that I would stick with `\providecommand{\subtitle}[1]{}` and delegate the choice of rendering it or not to the stylesheet, at least for my own needs on my `dev` branch.

> [...] people might well expect that in PDF/LaTeX.

That may be an easy counterargument, but should people expect to have `institute` or whatever rendered with any stylesheet then?
Also what if you want to render `subtitle` with some stylesheet and not with others. This solution kind of twists your arm into rendering `subtitle` whatever you would want to do...

**Comment by adunning** [comment]
The point is that title, subtitle, author, date, abstract are all standard terms in pandoc, and should be rendered by default whenever it is reasonable in a given format. Something like institute is not in any template. If you don't want the subtitle to appear, simply remove it from the template.

**Comment by xoolive** [comment]
Well `institute` is common in beamer presentations...

Unlike `title`, `subtitle` is not a default LaTeX command, so whether to 
render it or not is not obvious. I tend to think it is up to the 
stylesheet or documentclass to decide whether to print it or not, but 
wouldn't fight to death for that.

However my bottomline is that the solution implemented in pandoc should 
not overwrite a LaTeX stylesheet that would happen to not define 
`subtitle`.

**Comment by adunning** [comment]
Has anyone come up with a better method of handling this? This solution obviously is not ideal, but something should be done with the problem before there is another release. At the very least, a warning should be added to the README noting that subtitles will only render with scrartcl etc.

**Comment by adunning** [comment]
(I can submit a proposal for this if desired.)

**Comment by jgm** [comment]
+++ Andrew Dunning [Dec 16 15 19:13 ]:
>   Has anyone come up with a better method of handling this? This solution
>   obviously is not ideal, but something should be done with the problem
>   before there is another release. At the very least, a warning should be
>   added to the README noting that subtitles will only render with
>   scrartcl etc.

I think that's what we should do (the warning).

**Comment by adunning** [comment]
Added in <https://github.com/jgm/pandoc/pull/2594>.

**Comment by xoolive** [comment]
I also like the warning option

**Pull request closed without merging**
