### PR TITLE
Update default.latex

### PR DESCRIPTION
**Pull request by dluciv**
LaTeX template fix for https://github.com/jgm/pandoc-templates/issues/180

### CODE REVIEW

**Comment by dluciv** [comment]
Cumulative pull request:

- LaTeX template fix for #180.
- LaTeX template option to specify `\defaultfontfeatures` -- default value crashes `xelatex` on cyrillic documents.
- HTML & HTML5 marking content semantically. This can already be done using `include-before` & `include-after`, but enclosing body within dedicated tag looks more consistent.

**Comment by jgm** [comment]
Please split this into separate pull requests so we can
consider them individually.  Big omnibus PRs are not likely
to be merged!

+++ Dmitry V. Luciv [Jan 31 16 02:18 ]:

**Comment by dluciv** [comment]
Ok, thank you. Created two requests. One for {pdf/xe}latex, one for html[5].

**Comment by jgm** [comment]
Thanks!

+++ Dmitry V. Luciv [Jan 31 16 11:21 ]:

**Pull request closed without merging**
