### PR TITLE
Add $varlang$ for polyglossia

### PR DESCRIPTION
**Pull request by twsh**
To use a variant of English, such as British English, polyglossia.sty requires a 'variant' option. Adding this variable to the template allows that.

### CODE REVIEW

**Comment by ousia** [comment]
Sorry, @twsh, but there should be another method of doing this. We have too many language variables in `pandoc`.

I don’t use LaTeX myself anymore, but both polyglossia and babel should uses the standard way of naming languages outside LaTeX (such as `en-GB`).

Let me contact the current maintainers of polyglossia and babel to check whether this could be implemented.

**Comment by twsh** [comment]
Fair enough. It would be a step forward if polyglossia allowed setting 'british' directly, even.

**Comment by ousia** [comment]
> Fair enough. It would be a step forward if polyglossia allowed setting 'british' directly, even.

@twsh, I sent the requests.

> One problem with the current situation is that setting the pandoc language as 'british' means the file won't compile with xelatex.

The problem with setting anything different from `en-UK` is that it won’t work outside LaTeX.

**Comment by twsh** [comment]
Here is a way I thought of to make en-GB work:

```
\usepackage{etoolbox}
\newtoggle{en-GB}
$if(lang)$
\toggletrue{$lang$}
$endif$
\iftoggle{en-GB}{%
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
    \usepackage[british]{babel}
\else
    \usepackage{polyglossia}
    \setmainlanguage[variant=british]{english}
    \usepackage[style=british]{csquotes}
}{}
```
Of course a toggle would need to be defined for every language alias that polyglossia and babel support.

**Comment by jgm** [comment]
Ultimately I think the best solution might be to have pandoc
do the needed conversions behind the scenes.  So you could
specify `lang` in your document using the ISO-639 codes,
and pandoc would set variables like `babel-lang` and
`polyglossia-lang` and `polyglossia-variant` accordingly.

See #1667.

**Comment by twsh** [comment]
I'm realising how complicated this is after reading the issue you link to. Having Pandoc do it behind the scenes would obviously be great. That polyglossia.sty uses its different system for British (which csquotes.sty doesn't pick up on) makes it more complicated.

**Comment by ousia** [comment]
> Ultimately I think the best solution might be to have pandoc do the needed conversions behind the scenes. So you could specify `lang` in your document using the ISO-639 codes, and pandoc would set variables like `babel-lang` and `polyglossia-lang` and `polyglossia-variant` accordingly.

@jgm, I’m contacting babel and polyglossia developers to see whether it would be possible that both packages accept ISO-639 codes as languages. Do you want me to investigate this further?

BTW, in pull request #101, there is a proposal about changing all language variables to `language` and `other-languages`. It also includes language synonyms for ConTeXt (this actually fixes jgm/pandoc#1667 for ConTeXt).

Could you check it? Sorry for asking again, but I can’t make other pull requests unless that one has been processed.

**Comment by mb21** [comment]
the issue this solves is fixed as part of https://github.com/jgm/pandoc-templates/pull/114

**Pull request closed without merging**
