### PR TITLE
Use parskip.sty when the 'indent' option isn't set

### PR DESCRIPTION
**Pull request by twsh**

### CODE REVIEW

**Comment by adunning** [comment]
Looking at the code for this package, it looks as if it provides slightly better results than using `\setlength` directly. It's included with BasicTeX and the TeX Live latexrecommended collection, so it's probably safe to use it.

**Comment by twsh** [comment]
That was my impression too.

**Comment by adunning** [comment]
I suppose to be even safer, the package could only be used conditionally:

```tex
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
```

**Comment by twsh** [comment]
How do you decide whether that's necessary? You could imagine a case where any package is missing, but the templates don't load them all conditionally.

**Comment by adunning** [comment]
Packages that are in `collection-latexrecommended` may not be installed if one is running a minimal TeX Live installation; by contrast, something like `hyperref` is in `collection-latex`, and is basically guaranteed to be available on a recent system. If one can still render the document reasonably well without such packages, it makes sense to do so.

(You can see what is included in collections through the [texlive.tlpdb](http://tug.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb) file.)

**Comment by adunning** [comment]
If it clarifies things further, I believe the specific aim is to make it possible to render a simple document with a `scheme-basic` installation, which only includes `collection-basic` and `collection-latex` (though I'm not sure whether anyone has tested recently whether this actually works). BasicTeX for OS X corresponds to `scheme-small`.

**Comment by twsh** [comment]
I’ve used your conditional.

**Pull request merged**
