### PR TITLE
Add dvipsnames colors

### PR DESCRIPTION
**Pull request by xoolive**
Just a small convenient addition so be able to use more colours than `blue` and `red`. 
Rendering url in `blue` may make my eyes bleed, so I like to choose softer colors like :

```
urlcolor: MidnightBlue
```

### CODE REVIEW

**Comment by xoolive** [comment]
Note: I often get confused by the `dvipsnames` option, but you can use it regardless your rendering processing engine (`xelatex`, `dvipdfm`, `pdflatex`, etc.) so the fix remains universal.

**Comment by jgm** [comment]
If this adds a dependency on a new package `color`, then I'd prefer not to make it part of the default template.  It just makes it more likely that pandoc's PDF production won't work for someone, and it's not hard for someone like you to add this to a default template or use header includes.

**Comment by xoolive** [comment]
Thank your for your reply. Considering the fact that the package `color` is part of the `graphics` bundle, which is one of the col­lec­tions in the LaTeX ‘re­quired’ set of pack­ages, I guess it is pretty safe :+1: 

For reference, see http://www.ctan.org/pkg/color and http://www.ctan.org/pkg/graphics

**Comment by jgm** [comment]
OK, I guess this should be safe.
Now, with this change, I wonder if it would make sense to change the default link colors in the template to something less eyebleedy?

**Comment by xoolive** [comment]
Mmmmh, I don't know how to reach the perfect balance between standard/eyebleedy (red, blue, etc.) and beautiful but unavoidably more personal tastes. `prettyplotlib` [1] did a good job with colours by default for `python/matplotlib`, but I find that reaching this good balance is pretty hard.

I sold my soul to `MidnightBlue`, `BrickRed` and `OliveGreen` for my academic papers (I am still undecided for the yellowish tone), and those colours are actually the best (imho), but yet, my stylesheet is not built to be a stylesheet by default.

If you want to pick some default colours among the dvipsnames list, you can have an overview on the whole panel here: https://en.wikibooks.org/wiki/LaTeX/Colors

Anyway, I am interested by this matter, so please keep me updated 

[1] https://github.com/olgabot/prettyplotlib

**Pull request merged**
