### PR TITLE
 Added metadata `usepackage` and `hypersetup` to control the latex template options respectively

### PR DESCRIPTION
**Pull request by ickc**
# `\usepackage` and `\hypersetup` metadata keys

I added two metadata `usepackage` and `hypersetup` for use in template.latex

e.g.:

```yaml
usepackage:	physics,cancel
hypersetup:	bookmarksnumbered,pdfpagelabels,pagebackref,hypertexnames=false,linktocpage=true
```

will added the 2 packages in the `\usepackage` command, and those hypersetup in the `\hypersetup` command.

I think using different packages and tailoring the hypersetup is a common thing to do. So rather than personalizing it per template basis, may be it is better to provide a standard metadata key to do those in YAML front matter. Of course it doesn't provide all the freedoms (e.g. provide options in usepackage) but it is general and useful enough. I hope you can consider to make it official.

By the way, currently there's a way to "hack" the default template to do this:

```yaml
fontfamily:	lmodern,physics,cancel
```

But it is better to make a dedicated metadata key in the default template.

# Using `-N, --number-sections` in templates?

There's actually one more thing I wanted to do but I can't: there is a pandoc command line option `-N, --number-sections` to make the sections numbered. I wanted to added `bookmarksnumbered` to `hypersetup if this command line option is used. I tried `$number-sections$` but it doesn't work. Are there any way to do this?

### CODE REVIEW

**Comment by ickc** [comment]
Are there any interests in providing these 2 additional metadata? If no, should this be closed?

**Comment by tarleb** [comment]
I'm next to clueless with regard to the LaTeX template, but most templates, including the LaTeX template, support the `header-include` metadata field.  This means one could explicitly write

    header-include:
      - \usepackage{physics}
      - \usepackage{cancel}

I think using this general option is preferable to a specialized `usepackage` option.

I've never used hypersetup and don't know who it works, so I can't say much about that.

**Comment by ickc** [comment]
> support the header-include metadata field

Are you sure it can be added as a metadata in the yaml front matter?

I tested it using

```yml
---
header-include:
  - \usepackage{physics}
  - \usepackage{cancel}
...

testing
```

with

```bash
pandoc -s -o testing.tex testing.md
```

but the output TeX does not contain those `usepackage`.

According to the doc:

>Some variables are set automatically by pandoc. These vary somewhat depending on the output format, but include metadata fields as well as the following:
> ...
> **`header-includes`**
> contents specified by `-H`/`--include-in-header` (may have multiple values)

But I agree the idea can be done through `--include-in-header`.

> I've never used hypersetup and don't know how it works, so I can't say much about that.

`hypersetup` can be used multiple times so the same idea applies.

Basically my question is if the suggested 2 metadata keys would be considered. If no, I will actually use `--include-in-header` to do it. I am actually in the progress of getting rid of custom templates and use `--include-in-header` whenever possible.

In terms of `usepackage`, I actually prefer `fontfamily: lmodern,physics,cancel` if the `usepackage` metadata is not accepted. Since it then does not depends on external `--include-in-header` nor custom template, making it more portable.

**Comment by ickc** [comment]
I accidentally deleted the branch when I'm cleaning up my mess, and that accidentally closed the pull request. Anyway, I'll keep it closed unless they are considered. `Stale branches` like this probably means they are not interested it.

**Pull request closed without merging**
