### PR TITLE
Institute

### PR DESCRIPTION
**Pull request by twsh**
I’ve added the option to set an ‘institute’ variable which will be used in Beamer’s `\institute` command.

### CODE REVIEW

**Comment by twsh** [comment]
This needs to be rebased but I won’t be able to do it soon.

**Comment by twsh** [comment]
Perhaps this should use `$author.affiliation$` instead?

**Comment by jgm** [comment]
@twsh, you've understood precisely the reason I've been reluctant to make this change.

**Comment by twsh** [comment]
Just having $institute$ wouldn’t have that problem but might not be worthwhile.

**Comment by AndiH** [comment]
I would second the addition of `$institute$` to the beamer template. It's a macro provided by beamer, used by many templates. So, we should be able to set it, as shown by @twsh's commit 236f433.

For the time being,
```yaml
header-includes:
    - \institute{Some University}
```
could be a work-around…

**Pull request closed without merging**
