### PR TITLE
typeface invocation in ConTeXt

### PR DESCRIPTION
**Pull request by ousia**
@adunning, here you have the correct invocation in ConTeXt.

The only drawback is that if the user selects a custom typeface for other than the serif font, `mainfont` has to be defined also.

### CODE REVIEW

**Comment by adunning** [comment]
That seems to work.

**Comment by ousia** [comment]
@adunning, many thanks your testing.

@jgm, I think it is worth to include this code in the next bugfix release, since right now ConTeXt documents would be blank (no text included), if the user didn’t specify either the `mainfont` or `fontsize` variables.

**Comment by adunning** [comment]
Do you have a test document for this? Using the released version of the template, I am not seeing this behaviour.

**Comment by adunning** [comment]
(That is not to say that the change should not be made; I am only wondering why we are seeing different results.)

**Comment by jgm** [comment]
+++ Pablo Rodríguez [Nov 16 15 11:21 ]:
>   @jgm, I think it is worth to include this code in the next bugfix
>   release, since right now ConTeXt documents would be blank (no text
>   included), if the user didn’t specify either the mainfont or fontsize
>   variables.

Really?  I just did `pandoc README -o r.pdf -t context` and
got a non-blank document (looks quite good actually).

**Comment by ousia** [comment]
@adunning, sorry that was my fault.

I hadn’t tested the template itself. My test was the sample code with `\definefontfamily[mainface][serif][]`. And this causes the problem.

You’re right. The only issue with current template is that `sansfont` and `monofont` won’t be recognized. (Or do they work in your samples.)

**Comment by adunning** [comment]
Rik Kabel adds on pandoc-discuss:

> The \setupbodyfont[mainfont...] directive is placed too early. ConTeXt delays a number of internal settings involving fonts until the \setupbodyfont directive is encountered. By placing it high-up in the template, a user is not able to usefully perform additional font diddling (a technical term, I assure you) by way of a header include file. Generally, I find that \setupbodyfont should be the directive immediately preceding \starttext.

**Comment by adunning** [comment]
More ways in which ConTeXt font usage could be improved:

- `rscale=auto` should be added (try combining Menlo with Palatino), i.e. the equivalent of `Scale=MatchLowercase` in `fontspec`
- ConTeXt doesn't seem to provide a fallback by default (e.g. Greek), and it would be good to define one.

**Comment by ousia** [comment]
@adunning, which fallback font do you propose?

**Comment by ousia** [comment]
Closing this merge request myself, since there is a problem with ConTeXt stable version provided with TeX Live 2015.

I will propose a new merge request.

**Pull request closed without merging**
