### PR TITLE
Disable section title pages in beamer when natbib is used

### PR DESCRIPTION
**Pull request by yihui**
The commands `\AtBeginPart{}`, `\AtBeginSection{}`, `\AtBeginSubsection{}` in the default beamer template do not work with `--natbib`. A minimal reproducible example:

test.md

```md
---
title: "Untitled"
author: "Someone"
date: "March 11, 2015"
---

# The First Section

## A Subsection

Content [@R-base].
```

test.bib

```
@Manual{R-base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2015},
  url = {https://www.R-project.org/},
}
```

Convert the Markdown document to beamer:

```
pandoc -s -o test.tex -t beamer --natbib --bibliography=test.bib test.md
```

Compile the tex file to PDF:

```
pdflatex test.tex
bibtex test
pdflatex test.tex
```

Then you will get this error message:

```
3] (./test.bbl
! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.1 \begin{thebibliography}{1}
                              
? 
```

```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

$ bibtex --version
BibTeX 0.99d (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 Oren Patashnik.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the BibTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the BibTeX source.
Primary author of BibTeX: Oren Patashnik.
```

It will be nicer if the underlying LaTeX issue can be fixed instead of disabling this feature.

### CODE REVIEW

**Comment by jgm** [comment]
Any idea what the underlying incompatibility is?

**Comment by jgm** [comment]
I'm guessing the issue is this.  The `\bibliography` command creates its own new section.  But the macros `\AtBeginSection` etc. assume that any section command will occur *outside* a `frame` environment.

Btw, I've confirmed that it's only `\AtBeginSection` that is causing this.

**Comment by jgm** [comment]
I came up with a nicer fix that doesn't disable section slides when you use natbib.

**Comment by yihui** [comment]
Thanks! Just tested it, and it works well.

**Pull request closed without merging**
