### PR TITLE
Add hyphen option to url

### PR DESCRIPTION
**Pull request by JelteF**
This will break long urls. https://tex.stackexchange.com/questions/3033/forcing-linebreaks-in-url

### CODE REVIEW

**Comment by wilx** [comment]
I second the change. It at least improves line wrapping of long URL with dashes in them.

However the patch needs rebasing.

**Comment by jgm** [comment]
I'll merge this if it is rebased.

**Comment by jgm** [comment]
Closing in favor of #233

**Comment by JelteF** [comment]
Glad to see this merged, even though I didn't update the pull request.

**Pull request closed without merging**
