### PR TITLE
Section titles

### PR DESCRIPTION
**Pull request by twsh**
Add an option to set title pages for sections

### CODE REVIEW

**Comment by adunning** [comment]
Making this optional is a good idea, but I wonder whether it should be on by default.

There's a stray merge commit in there, by the way.

**Comment by twsh** [comment]
I was thinking that the default behaviour should be as close to plain Beamer as possible. But I can do it the other way around if that's better.

**Comment by twsh** [comment]
Is there an easy way to fix the stray merge commit? I'm fairly ignorant about Git(Hub).

**Comment by adunning** [comment]
That was more of a query than a specific recommendation. The approach of sticking to the standard behaviour wherever possible is a good principle.

That merge issue is one of the annoyances of the way GitHub Desktop works; it doesn't occur if you modify the file through the web interface. You can fix the commits by rebasing; see <https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request>.

**Comment by twsh** [comment]
Thanks. I think I've fixed it.

**Comment by adunning** [comment]
Looks like it. Thanks!

**Comment by jgm** [comment]
I think `section-titles` should be the default.  It's not default in Beamer, but this way the Beamer output matches output from the HTML slide formats.

**Comment by twsh** [comment]
Should I change it to something like this?
```
$if(no-section-titles)$
$else$
...
$endif$
```

**Comment by jgm** [comment]
No, better to keep `section-titles`, and we can set a
default of True in the latex writer.

+++ Thomas Hodgson [Dec 15 15 16:12 ]:

**Comment by twsh** [comment]
By the way, is the `\let\partnumber\relax` etc. there to solve a particular problem? Is it necessary?

**Comment by jgm** [comment]
@twsh - see commit 150f3ce9c67a2b4c948fcdc5793344bf8b53072b for the reason.

**Pull request merged**
