### PR TITLE
html: Wrap document body in <div>

### PR DESCRIPTION
**Pull request by bgamari**
This enables the user to easily center the document body and constrain
its width.

### CODE REVIEW

**Comment by bgamari** [comment]
Ping.

**Comment by jgm** [comment]
Why do you need a div?  Can't you apply styles directly to the `body` element?

**Comment by bgamari** [comment]
@jgm, There is no way to both center and constrain the width of the document by styling the `<body>` tag alone (as far as I know).

**Comment by nkalvi** [comment]
@bgamari Have you tried
```
html {
  max-width: 600px;
  margin: 0 auto;
}
```
Of course vary the width as needed.

**Comment by bgamari** [comment]
@nkalvi indeed that works. Fair enough, I suppose this is sufficient.

**Pull request closed without merging**
