### PR TITLE
Semantically enclose content for HTML & HTML5 targets.

### PR DESCRIPTION
**Pull request by dluciv**
Can already be done using include-before and include-after, but looks more consistent as suggested.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks - but I'd rather keep it simple.

**Comment by dluciv** [comment]
It was not created to make things complicated =)

It was initially needed to allow writing scripts, etc. to manipulate content.

But still can be done using `include-before` and `include-after` though.

**Comment by jgm** [comment]
+++ Dmitry V. Luciv [Mar 19 16 14:53 ]:
>   It was not created to make things complicated =)

Oh, I didn't mean to suggest that it was.  But it's
impossible to make the default template meet everyone's
needs.  Some will want the div, others will prefer it not
be there.

Can't you get at the content in scripts anyway?
Contents of the body element.

**Comment by dluciv** [comment]
Sure, no problem  for me =)

**Pull request closed without merging**
