### PR TITLE
conform all templates with language and other-languages (and add ISO-639 language codes for ConTeXt)

### PR DESCRIPTION
**Pull request by ousia**
@jgm, since pandoc can only write ConTeXt documents, I added language synonyms for ISO-639 codes in languages supported by ConTeXt.

This should partially fix jgm/pandoc#1667, as far as ConTeXt is concerned.

### CODE REVIEW

**Comment by ousia** [comment]
@jgm, the second commit wasn’t intended to be in the merge request (but it seems to be automatically added when pushing to my fork repository at GitHub [or I missed something]).

There is nothing wrong with the second commit. I’m just not sure whether `language` should be deployed instead of `lang` (as already asked in the mailing list).

**Comment by ousia** [comment]
@jgm, I replaced all `lang` occurrences in templates with the `language` YAML field. I also adapted `other-languages` for the LaTeX templates.

**Comment by mb21** [comment]
@ousia I don't think that you need the `\installlanguage` commands in `default.context`, but adding [`\language`](http://wiki.contextgarden.net/Command/language) in addition to `\mainlanguage` would be good.

**Comment by ousia** [comment]
> @ousia I don't think that you need the `\installlanguage` commands in `default.context`, but adding `\language` in addition to `\mainlanguage` would be good.

Many thanks for your comment, @mb21.

Sorry, but I’m afraid i don’t get your proposals.

`\installlanguage[de-CH][de-ch]` is required to set up the right language for a document with the following metadata:

``` markdown
---
title: Unser Schweizer Standpunkt
author: Carl Spitteler
lang: de-CΗ
...

So ungern als möglich trete ich aus meiner Einsamkeit in die Öffentlichkeit, um vor Ihnen
über ein Thema zu sprechen, das mich scheinbar nichts angeht.
```

Without the above `\installlanguage`, ConTeXt would hyphenate the text following English hyphenation rules.

`\installlanguage` doesn’t install anything, but it only defines language synonyms.

I think these language synonyms are required in `default.context` to match BCP-47 language values (and some ISO 639 ones, such as `grc`).

Please, correct me if I’m missing something from your first proposal (about removing `\installlanguage`).

And about your second proposal, why is `\language` required in `default.context`?

ConTeXt doesn’t need to know which languages the document contains. This behavior differs from LaTeX.

The following sample shows it:

``` tex
\mainlanguage[es]
\setupbodyfont[dejavu]
\starttext
\hyphenatedword{legibilidad}

\de\hyphenatedword{Lesbarkeit}

\en\hyphenatedword{legibility}

\agr\hyphenatedword{χαλεπὰ τὰ καλά}
\stoptext
```

This is the output:

language

Or am I also missing something in your second proposal (to add `\language` in `default.context`)?

**Comment by mb21** [comment]
I see, but I think we can get rid of `\installlanguage` by simply lowercasing the BCP-47 language values (e.g. `de-CH` to `de-ch`) in the ConTeXt Writer—I'll prepare a pull request soon.

If I understand correclty `\mainlanguage` sets the to change structural labels (chapter, part, etc.) and `\language` the hyphenation, so we need both.

**Comment by ousia** [comment]
> I see, but I think we can get rid of `\installlanguage` by simply lowercasing the BCP-47 language values (e.g. `de-CH` to `de-ch`) in the ConTeXt Writer—I'll prepare a pull request soon.

No, this would only work with German and Arabic, but these are rather exceptions. It won’t work with any other BCP-47 language. ConTeXt doesn’t have language values for `language-region`, such as in `it-iT`, `es-ES` (only `it` and `es` are defined).

And even for pure ISO 639 values, ConTeXt has different values. For example, `uk` is Ukrainian in ISO 639 and British English in ConTeXt. Greek is `el` in iSO 639 and `gr` in ConTeXt. Or Hebrew is `he` in ISO 639 and `il` in ConTeXt.

Sorry, but I’m afraid that `default.context` needs these language synonym definitions with `\installlanguage`.

> If I understand correctly `\mainlanguage` sets the to change structural labels (chapter, part, etc.) and `\language` the hyphenation, so we need both.

Yes, this is the way it works, but why do we need `\language` in `default.context`?

pandoc should have a special language attribute to deal with it accordingly in any format that supports language (jgm/pandoc#895). This is also the reason why identifiers, classes and languages should be granted to each element in pandoc (jgm/pandoc#1966).

**Comment by mb21** [comment]
I see, agreed.

But I think it's more robust to handle the conversion in pandoc itself, rather than in the templates. For example, `de-US` is technically a valid BCP47 string (German, as spoken in the US), so I wrote some code that falls back on the first part (`de`) in cases like that, see [pandoc pull 2369](https://github.com/jgm/pandoc/pull/2369).

**Comment by jgm** [comment]
+++ mb21 [Aug 20 15 08:36 ]:
>I see, agreed.
>
>But I think it's more robust to handle the conversion in pandoc itself, rather than in the templates. For example, `de-US` is technically a valid BCP47 string (German, as spoken in the US), so I wrote some code that falls back on the first part (`de`) in cases like that, see [pandoc pull 2369](https://github.com/jgm/pandoc/pull/2369).

Yes, I think it's better to handle this in pandoc.

**Comment by mb21** [comment]
This issue should be closed since [pandoc pull 2369](https://github.com/jgm/pandoc/pull/2369) was merged.

**Pull request closed without merging**
